name: lorapro-vit
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - pyyaml
  - pip:
      - transformers
      - datasets
      - accelerate
      - peft
      - evaluate
      - timm
      - rich
